"""Type stubs for thorvg_cython.sw_canvas."""

from __future__ import annotations

from .thorvg import Canvas, Colorspace, PixelBuffer, Result


class SwCanvas(Canvas):
    """Software canvas with integrated pixel buffer and PEP 3118 support."""
    def __init__(
        self, w: int = 0, h: int = 0, cs: int = 0, engine_option: int = 1,
    ) -> None: ...
    def __getbuffer__(self, buffer: object, flags: int) -> None: ...
    def __releasebuffer__(self, buffer: object) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def resize(self, w: int, h: int, cs: int = -1) -> Result: ...
    @property
    def buffer(self) -> PixelBuffer | None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def colorspace(self) -> Colorspace: ...
    def clear(self) -> None: ...
